disableKinds = ["RSS", "sitemap"]
baseURL = 'https://ChRomain.github.io/portfolio/'
theme = "blowfish"
languageCode = "fr"
title = "Travel"

[params]
  showRecent = false
  mainSections = ["gallery"]
  showDate = false
  showReadingTime = false
  showEdit = false
  showSearch = false
  showSocial = true
  showSocialInHeader = true
  [params.homepage]
    layout = "card"
    showRecent = true
    showRecentItems = 1000
    showTitle = false
    cardView = true
  [params.gallery]
    enable = true
  [params.article]
    showDate = false
    showReadingTime = false
    showAuthor = false
    [params.footer]
      showCopyright = false
      showPoweredBy = false

[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/romain.charretteur"

# --- NIVEAU 1 : ACCUEIL & CONTINENTS ---
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Amérique du Nord"
  identifier = "menu_am_nord"
  url = "#"
  weight = 10

[[menu.main]]
  name = "Amérique Centrale"
  identifier = "menu_am_central"
  url = "#"
  weight = 20

[[menu.main]]
  name = "Asie"
  identifier = "menu_asie"
  url = "#"
  weight = 30

[[menu.main]]
  name = "Europe"
  identifier = "menu_europe"
  url = "#"
  weight = 40

# --- NIVEAU 2 : PAYS ---
[[menu.main]]
  name = "Canada"
  identifier = "menu_canada"
  parent = "menu_am_nord"
  url = "#"
  weight = 1

[[menu.main]]
  name = "USA"
  identifier = "menu_usa"
  parent = "menu_am_nord"
  url = "#"
  weight = 2

[[menu.main]]
  name = "France"
  identifier = "menu_france"
  parent = "menu_europe"
  url = "#"
  weight = 1

[[menu.main]]
  name = "Italie"
  identifier = "menu_italie"
  parent = "menu_europe"
  url = "#"
  weight = 2

# --- NIVEAU 3 : VILLES ---

# CANADA
[[menu.main]]
  name = "Montréal"
  parent = "menu_canada"
  url = "/gallery/montreal/"
  weight = 1

[[menu.main]]
  name = "Ottawa"
  parent = "menu_canada"
  url = "/gallery/ottawa/"
  weight = 2

[[menu.main]]
  name = "Québec"
  parent = "menu_canada"
  url = "/gallery/quebec/"
  weight = 3

[[menu.main]]
  name = "Toronto"
  parent = "menu_canada"
  url = "/gallery/toronto/"
  weight = 4

[[menu.main]]
  name = "Autres"
  parent = "menu_canada"
  url = "/gallery/canada/"
  weight = 5

# USA
[[menu.main]]
  name = "Boston"
  parent = "menu_usa"
  url = "/gallery/boston/"
  weight = 1

[[menu.main]]
  name = "Cape Cod"
  parent = "menu_usa"
  url = "/gallery/cape_cod/"
  weight = 2

[[menu.main]]
  name = "Maine"
  parent = "menu_usa"
  url = "/gallery/maine/"
  weight = 3

[[menu.main]]
  name = "New Hampshire"
  parent = "menu_usa"
  url = "/gallery/new_hampshire/"
  weight = 4

[[menu.main]]
  name = "New York"
  parent = "menu_usa"
  url = "/gallery/new_york/"
  weight = 5

[[menu.main]]
  name = "Niagara Falls"
  parent = "menu_usa"
  url = "/gallery/niagara_falls/"
  weight = 6

[[menu.main]]
  name = "Philadelphia"
  parent = "menu_usa"
  url = "/gallery/philadelphie/"
  weight = 7

[[menu.main]]
  name = "Vermont"
  parent = "menu_usa"
  url = "/gallery/vermont/"
  weight = 8

[[menu.main]]
  name = "Washington"
  parent = "menu_usa"
  url = "/gallery/washington/"
  weight = 9

# FRANCE
[[menu.main]]
  name = "Bordeaux"
  parent = "menu_france"
  url = "/gallery/bordeaux/"
  weight = 1

[[menu.main]]
  name = "Corse"
  parent = "menu_france"
  url = "/gallery/corse/"
  weight = 2

[[menu.main]]
  name = "Finistère"
  parent = "menu_france"
  url = "/gallery/finistere/"
  weight = 3

[[menu.main]]
  name = "Lyon"
  parent = "menu_france"
  url = "/gallery/lyon/"
  weight = 4

[[menu.main]]
  name = "Paris"
  parent = "menu_france"
  url = "/gallery/paris/"
  weight = 5

# ITALIE
[[menu.main]]
  name = "Naples"
  parent = "menu_italie"
  url = "/gallery/naples/"
  weight = 1

# DIRECTS (NIVEAU 2)
[[menu.main]]
  name = "Guatemala"
  parent = "menu_am_central"
  url = "/gallery/guatemala/"
  weight = 1

[[menu.main]]
  name = "Indonésie"
  parent = "menu_asie"
  url = "/gallery/indonesie/"
  weight = 1

[[menu.main]]
  name = "Monténégro"
  parent = "menu_europe"
  url = "/gallery/montenegro/"
  weight = 3